# Indexing and Selection 

In [2]:
import numpy as np

In [4]:
array = np.arange(10,200,9)
array

array([ 10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109, 118,
       127, 136, 145, 154, 163, 172, 181, 190, 199])

In [6]:
array[8]

np.int64(82)

In [9]:
array[ 4:  9: 2 ] #(start default=index 0 , Stop default= last index  , Jump/step size )

array([46, 64, 82])

In [ ]:
print(array)
np.where(array >= 100) # where ever your condition is True it will return its Index

[ 10  19  28  37  46  55  64  73  82  91 100 109 118 127 136 145 154 163
 172 181 190 199]


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),)

Indexing in 2D

In [17]:
arr_2d =np.arange(1,10).reshape(3,3) 
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[0] # all the values in 0th row

array([1, 2, 3])

In [26]:
arr_2d[1 : 2, 1 : 3] # [ Start row : End row , Start Column : End Column ] Note End {row, column} are excluded 

array([[5, 6]])

In [25]:
arr_2d[2: , : 2 ]

array([[7, 8]])

Fancy Indexing (aka Advance Indexing)

In [27]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
rows = [1,1,0,2,2,0]
column = [0,2,2,1,0,1]

arr_2d[rows, column]

array([4, 6, 3, 8, 7, 2])

In [30]:
array

array([ 10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109, 118,
       127, 136, 145, 154, 163, 172, 181, 190, 199])

In [31]:
array > 120

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])